config/routes.rb
FiveStrikesTest::Application.routes.draw do
  resources :tickers

  resources :games

  resources :players

  resources :teams

end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
end

app/models/ticker.rb
class Ticker < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  # GET /players.json
  def index
    @players = Player.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @player = Player.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/new
  # GET /players/new.json
  def new
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(params[:player])

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render json: @player, status: :created, location: @player }
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teams }
    end
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
    @team = Team.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @team }
    end
  end

  # GET /teams/new
  # GET /teams/new.json
  def new
    @team = Team.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @team }
    end
  end

  # GET /teams/1/edit
  def edit
    @team = Team.find(params[:id])
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(params[:team])

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render json: @team, status: :created, location: @team }
      else
        format.html { render action: "new" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teams/1
  # PUT /teams/1.json
  def update
    @team = Team.find(params[:id])

    respond_to do |format|
      if @team.update_attributes(params[:team])
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team = Team.find(params[:id])
    @team.destroy

    respond_to do |format|
      format.html { redirect_to teams_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tickers_controller.rb
class TickersController < ApplicationController
  # GET /tickers
  # GET /tickers.json
  def index
    @tickers = Ticker.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickers }
    end
  end

  # GET /tickers/1
  # GET /tickers/1.json
  def show
    @ticker = Ticker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticker }
    end
  end

  # GET /tickers/new
  # GET /tickers/new.json
  def new
    @ticker = Ticker.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticker }
    end
  end

  # GET /tickers/1/edit
  def edit
    @ticker = Ticker.find(params[:id])
  end

  # POST /tickers
  # POST /tickers.json
  def create
    @ticker = Ticker.new(params[:ticker])

    respond_to do |format|
      if @ticker.save
        format.html { redirect_to @ticker, notice: 'Ticker was successfully created.' }
        format.json { render json: @ticker, status: :created, location: @ticker }
      else
        format.html { render action: "new" }
        format.json { render json: @ticker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickers/1
  # PUT /tickers/1.json
  def update
    @ticker = Ticker.find(params[:id])

    respond_to do |format|
      if @ticker.update_attributes(params[:ticker])
        format.html { redirect_to @ticker, notice: 'Ticker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickers/1
  # DELETE /tickers/1.json
  def destroy
    @ticker = Ticker.find(params[:id])
    @ticker.destroy

    respond_to do |format|
      format.html { redirect_to tickers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tickers_helper.rb
module TickersHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :teamHomeID %><br />
    <%= f.number_field :teamHomeID %>
  </div>
  <div class="field">
    <%= f.label :teamAwayID %><br />
    <%= f.number_field :teamAwayID %>
  </div>
  <div class="field">
    <%= f.label :goalsHome %><br />
    <%= f.number_field :goalsHome %>
  </div>
  <div class="field">
    <%= f.label :goalsAway %><br />
    <%= f.number_field :goalsAway %>
  </div>
  <div class="field">
    <%= f.label :gameID %><br />
    <%= f.number_field :gameID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <tr>
    <th>Teamhomeid</th>
    <th>Teamawayid</th>
    <th>Goalshome</th>
    <th>Goalsaway</th>
    <th>Gameid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.teamHomeID %></td>
    <td><%= game.teamAwayID %></td>
    <td><%= game.goalsHome %></td>
    <td><%= game.goalsAway %></td>
    <td><%= game.gameID %></td>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Teamhomeid:</b>
  <%= @game.teamHomeID %>
</p>

<p>
  <b>Teamawayid:</b>
  <%= @game.teamAwayID %>
</p>

<p>
  <b>Goalshome:</b>
  <%= @game.goalsHome %>
</p>

<p>
  <b>Goalsaway:</b>
  <%= @game.goalsAway %>
</p>

<p>
  <b>Gameid:</b>
  <%= @game.gameID %>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FiveStrikesTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :teamID %><br />
    <%= f.number_field :teamID %>
  </div>
  <div class="field">
    <%= f.label :spielerName %><br />
    <%= f.text_field :spielerName %>
  </div>
  <div class="field">
    <%= f.label :spielerID %><br />
    <%= f.number_field :spielerID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <tr>
    <th>Teamid</th>
    <th>Spielername</th>
    <th>Spielerid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.teamID %></td>
    <td><%= player.spielerName %></td>
    <td><%= player.spielerID %></td>
    <td><%= link_to 'Show', player %></td>
    <td><%= link_to 'Edit', edit_player_path(player) %></td>
    <td><%= link_to 'Destroy', player, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Teamid:</b>
  <%= @player.teamID %>
</p>

<p>
  <b>Spielername:</b>
  <%= @player.spielerName %>
</p>

<p>
  <b>Spielerid:</b>
  <%= @player.spielerID %>
</p>


<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/tickers/_form.html.erb
<%= form_for(@ticker) do |f| %>
  <% if @ticker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticker.errors.count, "error") %> prohibited this ticker from being saved:</h2>

      <ul>
      <% @ticker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :actionID %><br />
    <%= f.number_field :actionID %>
  </div>
  <div class="field">
    <%= f.label :playerID %><br />
    <%= f.number_field :playerID %>
  </div>
  <div class="field">
    <%= f.label :tickerID %><br />
    <%= f.number_field :tickerID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickers/edit.html.erb
<h1>Editing ticker</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticker %> |
<%= link_to 'Back', tickers_path %>

app/views/tickers/index.html.erb
<h1>Listing tickers</h1>

<table>
  <tr>
    <th>Actionid</th>
    <th>Playerid</th>
    <th>Tickerid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tickers.each do |ticker| %>
  <tr>
    <td><%= ticker.actionID %></td>
    <td><%= ticker.playerID %></td>
    <td><%= ticker.tickerID %></td>
    <td><%= link_to 'Show', ticker %></td>
    <td><%= link_to 'Edit', edit_ticker_path(ticker) %></td>
    <td><%= link_to 'Destroy', ticker, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ticker', new_ticker_path %>

app/views/tickers/new.html.erb
<h1>New ticker</h1>

<%= render 'form' %>

<%= link_to 'Back', tickers_path %>

app/views/tickers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Actionid:</b>
  <%= @ticker.actionID %>
</p>

<p>
  <b>Playerid:</b>
  <%= @ticker.playerID %>
</p>

<p>
  <b>Tickerid:</b>
  <%= @ticker.tickerID %>
</p>


<%= link_to 'Edit', edit_ticker_path(@ticker) %> |
<%= link_to 'Back', tickers_path %>